# Generated by Django 5.0.9 on 2026-07-13 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="user_stance",
            field=models.CharField(
                choices=[("FOR", "For"), ("AGAINST", "Against")],
                default="FOR",
                max_length=10,
            ),
            preserve_default=False,
        ),
    ]
