# Generated by Django 5.0.9 on 2026-08-12 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0002_match_user_stance"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="match",
            name="share_slug",
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
