# Generated by Django 5.0.9 on 2026-08-01 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pending_login_token_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
