# Generated by Django 5.0.9 on 2026-07-13 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scorecard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logic_score', models.FloatField(blank=True, null=True)),
                ('evidence_score', models.FloatField(blank=True, null=True)),
                ('rhetoric_score', models.FloatField(blank=True, null=True)),
                ('adherence_score', models.FloatField(blank=True, null=True)),
                ('fallacies', models.JSONField(blank=True, default=list)),
                ('winner', models.CharField(blank=True, choices=[('USER', 'User'), ('AI', 'AI'), ('DRAW', 'Draw')], max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scorecard', to='matches.match')),
            ],
        ),
    ]
